#!/bin/sh
ln -s ../socketapi/condition.h .
ln -s ../socketapi/condition.icc .
ln -s ../socketapi/extsocketdescriptor.h .
ln -s ../socketapi/internetaddress.h .
ln -s ../socketapi/internetaddress.icc .
ln -s ../socketapi/internetflow.h .
ln -s ../socketapi/internetflow.icc .
ln -s ../socketapi/portableaddress.h .
ln -s ../socketapi/portableaddress.icc .
ln -s ../socketapi/randomizer.h .
ln -s ../socketapi/randomizer.icc .
ln -s ../socketapi/socketaddress.h .
ln -s ../socketapi/socketaddress.icc .
ln -s ../socketapi/synchronizable.h .
ln -s ../socketapi/synchronizable.icc .
ln -s ../socketapi/tdmessage.h .
ln -s ../socketapi/tdmessage.icc .
ln -s ../socketapi/tdstrings.h .
ln -s ../socketapi/tdstrings.icc .
ln -s ../socketapi/tdsystem.h .
ln -s ../socketapi/thread.h .
ln -s ../socketapi/thread.icc .
ln -s ../socketapi/tools.h .
ln -s ../socketapi/tools.icc .
ln -s ../socketapi/unixaddress.h .
ln -s ../socketapi/unixaddress.icc .
ln -s ../socketapi/tdin6.h .
